version: '3.8'
services:
  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
    ports:
      - ${API_PORT}:80
    depends_on:
      - db
    environment:
      DB_STRING: postgresql://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432
volumes:
  postgres_data:
