CREATE USER apiuser WITH PASSWORD '**TEMPLATE_DB_PASS**';
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO apiuser;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO apiuser;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO apiuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO apiuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO apiuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO apiuser;
